remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
Description: 
This repository will act as my portfolio as I work through my degree at BSU.

Thank you for a fun course this semester 
